### ISSUE TITLE
Make Webhook requests run in parallel

### ISSUE THREAD

**Issue by camirmas** [camirmas/grapple#8]
Right now we simply iterate through the list of `Hook`s with `Enum`. This can lead to bottlenecks in the case where we have a very large list of hooks to execute.

Possibly consider [GenStage](http://elixir-lang.org/blog/2016/07/14/announcing-genstage/), which will allow us to execute hooks in parallel. Once finished, hooks can be added to `Grapple.Logger`. Since hooks do not depend on one another and ordering doesn't matter, this distributed approach should provide strong benefits.

https://hexdocs.pm/gen_stage/Experimental.Flow.html
https://hexdocs.pm/gen_stage/Experimental.Flow.html#module-supervisable-flows

**Comment by slurmulon** [comment]
Having some clear-minded insomnia, going to take a slight stab at this.

**Comment by slurmulon** [comment]
Just did some basic wiring (added deps, imported into `hook.ex`). We should investigate this more: https://hexdocs.pm/gen_stage/Experimental.Flow.html#module-supervisable-flows
